<?php

namespace Container2VDPkHI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoogleOAuthControllerconnectGoogleCheckService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wLvy5Az.App\Controller\GoogleOAuthController::connectGoogleCheck()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wLvy5Az.App\\Controller\\GoogleOAuthController::connectGoogleCheck()'] = ($container->privates['.service_locator.wLvy5Az'] ?? $container->load('get_ServiceLocator_WLvy5AzService'))->withContext('App\\Controller\\GoogleOAuthController::connectGoogleCheck()', $container);
    }
}
