stages:
  - deploy

deploy_to_local:
  stage: deploy
  tags:
    - local 
  script:
    - cd /home/senyacm/github/php/www.MbsHosting.com
    - git pull origin develop 
    - docker-compose down -v
    - docker-compose up -d --build
  only:
    - develop  