version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:80"
    environment:
      APP_ENV: prod
      TRUSTED_PROXIES: 127.0.0.1
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped