nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost'] 
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        max_age: 3600
        hosts: []
        origin_regex: false
    paths:
        '^/api/': ~ 