<?php

namespace ContainerI3SMvMU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MsBLmIMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.msBLmIM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.msBLmIM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\GoogleOAuthController::connectGoogle' => ['privates', '.service_locator.wLvy5Az.App\\Controller\\GoogleOAuthController::connectGoogle()', 'getGoogleOAuthControllerconnectGoogleService', true],
            'App\\Controller\\GoogleOAuthController::connectGoogleCheck' => ['privates', '.service_locator.wLvy5Az.App\\Controller\\GoogleOAuthController::connectGoogleCheck()', 'getGoogleOAuthControllerconnectGoogleCheckService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\GoogleOAuthController:connectGoogle' => ['privates', '.service_locator.wLvy5Az.App\\Controller\\GoogleOAuthController::connectGoogle()', 'getGoogleOAuthControllerconnectGoogleService', true],
            'App\\Controller\\GoogleOAuthController:connectGoogleCheck' => ['privates', '.service_locator.wLvy5Az.App\\Controller\\GoogleOAuthController::connectGoogleCheck()', 'getGoogleOAuthControllerconnectGoogleCheckService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\GoogleOAuthController::connectGoogle' => '?',
            'App\\Controller\\GoogleOAuthController::connectGoogleCheck' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\GoogleOAuthController:connectGoogle' => '?',
            'App\\Controller\\GoogleOAuthController:connectGoogleCheck' => '?',
        ]);
    }
}
