<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKpCA76j\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKpCA76j/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKpCA76j.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKpCA76j\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKpCA76j\App_KernelDevDebugContainer([
    'container.build_hash' => 'KpCA76j',
    'container.build_id' => 'a949702b',
    'container.build_time' => 1753243615,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKpCA76j');
