<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'user_add' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/api/user/register']], [], [], []],
    'user_validate' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/api/user/login']], [], [], []],
    'user_get' => [[], ['_controller' => 'App\\Controller\\UserController::getByToken'], [], [['text', '/api/user/get']], [], [], []],
    'App\Controller\UserController::register' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/api/user/register']], [], [], []],
    'App\Controller\UserController::login' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/api/user/login']], [], [], []],
    'App\Controller\UserController::getByToken' => [[], ['_controller' => 'App\\Controller\\UserController::getByToken'], [], [['text', '/api/user/get']], [], [], []],
];
