<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'get_messages' => [[], ['_controller' => 'App\\Controller\\IPFSMessagesController::get'], [], [['text', '/api/message/get']], [], [], []],
    'add_message' => [[], ['_controller' => 'App\\Controller\\IPFSMessagesController::add'], [], [['text', '/api/message/add']], [], [], []],
    'user_add' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/api/user/register']], [], [], []],
    'user_auth' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/api/user/login']], [], [], []],
    'user_get' => [[], ['_controller' => 'App\\Controller\\UserController::getByToken'], [], [['text', '/api/user/get']], [], [], []],
    'user_validate' => [[], ['_controller' => 'App\\Controller\\UserController::validateUser'], [], [['text', '/api/user/validate']], [], [], []],
    'App\Controller\IPFSMessagesController::get' => [[], ['_controller' => 'App\\Controller\\IPFSMessagesController::get'], [], [['text', '/api/message/get']], [], [], []],
    'App\Controller\IPFSMessagesController::add' => [[], ['_controller' => 'App\\Controller\\IPFSMessagesController::add'], [], [['text', '/api/message/add']], [], [], []],
    'App\Controller\UserController::register' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/api/user/register']], [], [], []],
    'App\Controller\UserController::login' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/api/user/login']], [], [], []],
    'App\Controller\UserController::getByToken' => [[], ['_controller' => 'App\\Controller\\UserController::getByToken'], [], [['text', '/api/user/get']], [], [], []],
    'App\Controller\UserController::validateUser' => [[], ['_controller' => 'App\\Controller\\UserController::validateUser'], [], [['text', '/api/user/validate']], [], [], []],
];
