<?php

namespace ContainerZULm3R7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIPFSMessagesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\IPFSMessagesController' shared autowired service.
     *
     * @return \App\Controller\IPFSMessagesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/IPFSMessagesController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SecurityService.php';

        $container->services['App\\Controller\\IPFSMessagesController'] = $instance = new \App\Controller\IPFSMessagesController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\SecurityService'] ??= new \App\Service\SecurityService($container->getEnv('SECRET_KEY'))), ($container->privates['App\\Service\\UserService'] ?? $container->load('getUserServiceService')), ($container->privates['serializer'] ?? self::getSerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\IPFSMessagesController', $container));

        return $instance;
    }
}
