<?php

namespace ContainerVBs8ACU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGoogleOAuthControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GoogleOAuthController' shared autowired service.
     *
     * @return \App\Controller\GoogleOAuthController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GoogleOAuthController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SecurityService.php';

        $container->services['App\\Controller\\GoogleOAuthController'] = $instance = new \App\Controller\GoogleOAuthController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\SecurityService'] ??= new \App\Service\SecurityService($container->getEnv('SECRET_KEY'))));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\GoogleOAuthController', $container));

        return $instance;
    }
}
